numeric:
  plant_endpoint: "tcp://plant:5555"
  dt: 0.01
  max_steps: 4000  # 20 second long test
  timeout_ms: 5000
  log_file: "/app/logs/numeric_log.csv"

controller:
  type: "pid"
  kp: 18.0     # Aggressive proportional gain - proven optimal
  ki: 2.5      # Strong integral term for steady-state error elimination  
  kd: 10.0     # Strong derivative damping for overshoot control
  setpoint: 10.0  # Target altitude [m]

scenario:
  file: "/app/shared/scenarios/default.csv"
  enabled: false  # Use PID mode for simplified altitude control