numeric:
  plant_endpoint: "tcp://plant:5555"
  dt: 0.002
  max_steps: 1000
  timeout_ms: 5000
  log_file: "/app/logs/numeric_log.csv"

controller:
  type: "pid"
  kp: 1.0
  ki: 0.1
  kd: 0.01
  setpoint: [0.0, 0.0, 10.0]  # Target position (hover at 10m height)

scenario:
  file: "/app/shared/scenarios/default.csv"
  enabled: true