communication:
  enable_delay: false       # リアルタイム性能重視のため遅延無効
  # Enhanced delay configuration (for testing only)
  base_delay_ms: 0.5        # Base processing delay [ms]
  network_delay_ms: 1.0     # Network simulation delay [ms]
  jitter_ms: 0.2            # Jitter amplitude [ms]
  jitter_type: uniform      # uniform/gaussian/exponential

  # Backward compatibility (old parameters still supported)
  # processing_delay: 50.0
  # response_delay: 20.0
  # delay_variation: 10.0
plant:
  bind_address: tcp://0.0.0.0:5555
  dt: 0.01
  log_file: /app/logs/plant_log.csv
  max_steps: 1000
simulation:
  gravity: 9.81
  initial_position: 0.0
  initial_velocity: 0.0
  mass: 1.0
