plant:
  bind_address: "tcp://0.0.0.0:5555"
  dt: 0.01
  max_steps: 100000
  log_file: "/app/logs/plant_log.csv"

communication:
  # Heavy delay (poor network conditions)
  processing_delay: 10.0
  response_delay: 50.0
  delay_variation: 5.0
  enable_delay: true

simulation:
  mass: 1.0
  gravity: 9.81
  initial_position: 0.0
  initial_velocity: 0.0