
services:
  plant:
    build: ../plant
    container_name: hils-plant
    user: "1000:1000"
    networks: 
      - hilsnet
    ports:
      - "5555:5555"  # State publisher
    environment:
      - STEP_DT=${STEP_DT}
      - MAX_STEPS=${MAX_STEPS}
      - RUN_ID=${RUN_ID}
    volumes:
      - ../logs:/app/logs
    restart: "no"

  numeric:
    build: ../numeric
    container_name: hils-numeric
    user: "1000:1000"
    depends_on:
      - plant
    networks:
      - hilsnet
    ports:
      - "5556:5556"  # Command publisher
    environment:
      - PLANT_ENDPOINT=tcp://plant:5555
      - STEP_DT=${STEP_DT}
      - MAX_STEPS=${MAX_STEPS}
      - RUN_ID=${RUN_ID}
      - REALTIME_MODE=${REALTIME_MODE:-1}
    volumes:
      - ../logs:/app/logs
      - ../shared:/app/shared:ro
    command: ["python", "main_realtime.py"]
    restart: "no"

networks:
  hilsnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500

# Optional: For low-latency mode, uncomment the lines below and comment out the bridge network
# # services:
#   plant:
#     build: ../plant
#     container_name: hils-plant
#     network_mode: host
#     environment:
#       - PLANT_BIND=tcp://0.0.0.0:5555
#       - STEP_DT=${STEP_DT}
#     volumes:
#       - ../logs:/app/logs
#
#   numeric:
#     build: ../numeric  
#     container_name: hils-numeric
#     network_mode: host
#     depends_on:
#       - plant
#     environment:
#       - PLANT_ENDPOINT=tcp://127.0.0.1:5555
#       - STEP_DT=${STEP_DT}
#       - MAX_STEPS=${MAX_STEPS}
#     volumes:
#       - ../logs:/app/logs
#       - ../shared:/app/shared:ro