plant:
  bind_address: "tcp://0.0.0.0:5555"
  dt: 0.01
  max_steps: 100000
  log_file: "/app/logs/plant_log.csv"

communication:
  # High delay for testing communication impact
  processing_delay: 0.0     # Plant processing time (extreme case)
  response_delay: 0.0      # Response transmission time (poor network)
  delay_variation: 0.0      # Random jitter (very unstable)
  enable_delay: false         # Enable communication delay simulation

simulation:
  mass: 1.0
  gravity: 9.81    # Positive gravity value (handled correctly in code)
  initial_position: 0.0    # Z-axis only (altitude)
  initial_velocity: 0.0    # Z-axis velocity only